# Generated by Django 2.2 on 2021-12-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_userfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeed',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
